# Variables
@baseUrl = https://snemc-gemini-balance.hf.space
@authToken = sk-snemc123
@textModel = gemini-2.5-flash-preview-04-17
@imageGenModelGemini = gemini-2.0-flash-exp-image


###  工具调用 第一轮请求

POST {{baseUrl}}/v1/chat/completions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "model": "gemini-2.5-flash-preview-04-17",
    "messages": [
        {
            "role": "system",
            "content": "当你是一个中文助手，帮助用户回答问题,回答时需要使用中文。如果需要代码，请使用markdown格式输出，并明确指定代码语言类型，例如 ```python ... ```。"
        },
        {
            "role": "system",
            "content": "当用户的问题需要调用工具时，助手会自动选择工具并调用。"
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "北京的天气如何"   
                }
            ]
        }
    ],
    "tools": [
        {
            "type": "function",
            "function": {
                "name": "weather_tool",
                "description": "获取指定城市的天气信息",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "城市或县区，比如北京市、杭州市、余杭区等。"
                        }
                    },
                    "required": ["location"]
                }
            }
        }
    ],
    "tool_choice": "auto",
    "stream": false,
    "temperature": 0.7,
    "top_p": 1
}

### 回应

HTTP/1.1 200 OK
Date: Sat, 17 May 2025 11:23:39 GMT
Content-Type: application/json
Content-Length: 547
Connection: close
server: uvicorn
x-proxied-host: http://10.108.47.26
x-proxied-replica: jdwpudj6-mp2cy
x-proxied-path: /v1/chat/completions
link: <https://huggingface.co/spaces/snemc/gemini-balance>;rel="canonical"
x-request-id: 43gces
vary: origin, access-control-request-method, access-control-request-headers
access-control-allow-credentials: true

{
  "id": "chatcmpl-ac499fad-39cf-4a47-8356-8fab1a940e13",
  "object": "chat.completion",
  "created": 1747481019,
  "model": "gemini-2.5-flash-preview-04-17",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "好的，请稍等，我来帮您查询北京的天气。\n\n",
        "tool_calls": [
          {
            "index": 1,
            "id": "call_ewaqb5vukph6cjmfrgz8i17ys923n40x",
            "type": "function",
            "function": {
              "name": "weather_tool",
              "arguments": "{\"location\": \"\\u5317\\u4eac\\u5e02\"}"
            }
          }
        ]
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 98,
    "completion_tokens": 31,
    "total_tokens": 185
  }
}


### 工具调用 第二轮请求

POST {{baseUrl}}/v1/chat/completions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "model": "gemini-2.5-flash-preview-04-17",
    "messages": [
        {
            "role": "system",
            "content": "当用户的问题需要调用工具时，助手会自动选择工具并调用。如果工具已提供所需信息，请总结该信息并直接回答用户，不要再次调用同一工具获取相同信息"
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "北京的天气如何"   
                }
            ]
        },
        {
            "role": "assistant",
            "content": "好的，请稍等，我来查询北京的天气信息。\n",
            "tool_calls": [
                {
                    "index": 1,
                    "id": "call_zskeg8i0qdwcjm21h3fbpyvl6t7x49na",
                    "type": "function",
                    "function": {
                    "name": "weather_tool",
                    "arguments": "{\"location\": \"北京\"}"
                    }
                }
            ]
        },
        {
            "role": "tool",
            "tool_call_id": "call_zskeg8i0qdwcjm21h3fbpyvl6t7x49na",
            "content": {
                "type": "text",
                "text": "{\"location\": \"北京\", \"weather\": \"晴天\", \"temperature\": \"20℃\", \"humidity\": \"50%\", \"wind_speed\": \"3m/s\", \"wind_direction\": \"东风\", \"air_quality\": \"优\", \"air_quality_index\": \"100\", \"air_quality_level\": \"优\", \"air_quality_description\": \"空气质量良好，适宜户外活动。\"}"
            }
        }
    ],
    "tools": [
        {
            "type": "function",
            "function": {
                "name": "weather_tool",
                "description": "获取指定城市的天气信息",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "城市或县区，比如北京市、杭州市、余杭区等。"
                        }
                    },
                    "required": ["location"]
                }
            }
        }
    ],
    "tool_choice": "none",
    "stream": false,
    "temperature": 0.7,
    "top_p": 1
}

### 
HTTP/1.1 200 OK
Date: Sat, 17 May 2025 20:28:58 GMT
Content-Type: application/json
Content-Length: 487
Connection: close
server: uvicorn
x-proxied-host: http://10.108.47.26
x-proxied-replica: jdwpudj6-mp2cy
x-proxied-path: /v1/chat/completions
link: <https://huggingface.co/spaces/snemc/gemini-balance>;rel="canonical"
x-request-id: 3bWk0B
vary: origin, access-control-request-method, access-control-request-headers
access-control-allow-credentials: true

{
  "id": "chatcmpl-10fdce16-bfc9-4366-8ea1-69b4701e2bb6",
  "object": "chat.completion",
  "created": 1747513738,
  "model": "gemini-2.5-flash-preview-04-17",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "",
        "tool_calls": [
          {
            "index": 0,
            "id": "call_in3vfqt6ejg2hx4a1mucbsylod5w70p9",
            "type": "function",
            "function": {
              "name": "weather_tool",
              "arguments": "{\"location\": \"\\u5317\\u4eac\\u5e02\"}"
            }
          }
        ]
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 154,
    "completion_tokens": 15,
    "total_tokens": 238
  }
}